from flask import Blueprint, render_template, redirect, url_for

views_bp = Blueprint("views", __name__)

@views_bp.get("/")
def index(): return redirect(url_for("views.feed"))
@views_bp.get("/login")
def login(): return render_template("auth/login.html")
@views_bp.get("/register")
def register(): return render_template("auth/register.html")
@views_bp.get("/dashboard")
def dashboard(): return render_template("dashboard/index.html")
@views_bp.get("/feed")
def feed(): return render_template("feed/index.html")
@views_bp.get("/profile")
def profile(): return render_template("profile/index.html")
@views_bp.get("/jobs")
def jobs(): return render_template("jobs/index.html")
@views_bp.get("/skill-gap")
def skill_gap(): return render_template("skill_gap/index.html")
@views_bp.get("/recommendations")
def recommendations(): return render_template("recommendations/index.html")
@views_bp.get("/applications")
def applications(): return render_template("applications/index.html")
@views_bp.get("/saved-jobs")
def saved_jobs(): return render_template("saved_jobs/index.html")
@views_bp.get("/connections")
def connections(): return render_template("connections/index.html")
@views_bp.get("/messages")
def messages(): return render_template("messages/index.html")
@views_bp.get("/messages/<int:user_id>")
def message_thread(user_id): return render_template("messages/thread.html", other_id=user_id)
@views_bp.get("/recruiter")
def recruiter(): return render_template("recruiter/index.html")
@views_bp.get("/notifications")
def notifications(): return render_template("notifications/index.html")
@views_bp.get("/u/<int:user_id>")
def public_profile(user_id): return render_template("profile/public.html", user_id=user_id)
